# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22ce20004cb8388fdcb08acaf9996b394493b563d0006585ea685e478d955d6d369c24556c60c26c0ee8c1e62f1501f9674dcef57825e88d505d13d1b8374741

test:
  secret_key_base: 1320136bf9ebcc052963a66d7e8e81fceef10addd85d01a378cdc2fcfe5c96f3a1ebec6cabaae1f247ccb8f65a43790d196df93584656853213a163ce76d0272

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
